# Generated by Django 4.1.5 on 2023-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coffeedrinked_getintouch_happyclients_hoursworked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
