# Generated by Django 4.1.5 on 2023-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personalinfo_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birthdate',
            field=models.CharField(max_length=100),
        ),
    ]
