# Generated by Django 4.1.5 on 2023-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_personalinfo_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendamessage',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
