# Generated by Django 4.1.5 on 2023-01-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_myportfolionew_myportfolioall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolioaiandmachinelearning',
            name='image',
            field=models.ImageField(upload_to='media/Portfolio_images'),
        ),
        migrations.AlterField(
            model_name='myportfolioall',
            name='image',
            field=models.ImageField(upload_to='media/Portfolio_images'),
        ),
        migrations.AlterField(
            model_name='myportfolioapps',
            name='image',
            field=models.ImageField(upload_to='media/Portfolio_images'),
        ),
        migrations.AlterField(
            model_name='myportfoliowebsites',
            name='image',
            field=models.ImageField(upload_to='media/Portfolio_images'),
        ),
    ]
