# Generated by Django 4.1.6 on 2023-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_myportfolioall_alter_coffeedrinked_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfoliowebsites',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
