# Generated by Django 4.1.6 on 2023-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_myportfoliowebsites_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_1',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_2',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_3',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
    ]
