# Generated by Django 4.1.6 on 2023-02-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_myportfoliowebsites_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome',
            name='background',
        ),
        migrations.AddField(
            model_name='welcome',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/profile'),
        ),
    ]
