# Generated by Django 4.1.6 on 2023-02-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_welcome_background_welcome_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeDrinked',
            new_name='CoffeeDrank',
        ),
        migrations.AlterModelOptions(
            name='coffeedrank',
            options={'verbose_name_plural': 'Coffee Drank'},
        ),
    ]
