# Generated by Django 4.1.6 on 2023-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_coffeedrinked_coffeedrank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAndMachineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Ai and Machine learning Service',
            },
        ),
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'App Service',
            },
        ),
        migrations.CreateModel(
            name='WebsiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Website Service',
            },
        ),
    ]
