# Generated by Django 4.1.6 on 2023-02-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_aiandmachineservice_appservice_websiteservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiandmachineservice',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appservice',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websiteservice',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
