# Generated by Django 4.1.6 on 2023-02-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_aiandmachineservice_title_appservice_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_5',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_6',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_7',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_8',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
    ]
