# Generated by Django 4.1.6 on 2023-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_myportfoliowebsites_image_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='image_4',
            field=models.ImageField(null=True, upload_to='media/websites'),
        ),
    ]
