# Generated by Django 4.1.6 on 2023-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_myresumelanguages_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexpertise',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
