# Generated by Django 4.1.6 on 2023-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_myexpertise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiandmachineservice',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appservice',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websiteservice',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
