# Generated by Django 4.1.6 on 2023-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_aiandmachineservice_icon_appservice_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Hire Me',
            },
        ),
    ]
