# Generated by Django 4.1.6 on 2023-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_hireme'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireme',
            name='hire',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
