# Generated by Django 4.1.6 on 2023-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_hireme_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireme',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myportfolioaiandmachinelearning',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myportfolioapps',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myportfoliowebsites',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
