# Generated by Django 4.1.6 on 2023-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_hireme_miss_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireme',
            name='hire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myportfolioaiandmachinelearning',
            name='miss_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myportfolioapps',
            name='miss_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myportfoliowebsites',
            name='miss_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
