# Generated by Django 4.1.6 on 2023-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_facebook_github_instagram_linkedin_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twitter',
            name='miss_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
