# Generated by Django 4.1.6 on 2023-02-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_facebook_miss_link_github_miss_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='miss_link',
        ),
        migrations.RemoveField(
            model_name='github',
            name='miss_link',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='miss_link',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='miss_link',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='miss_link',
        ),
    ]
