from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(Welcome)
admin.site.register(CoffeeDrank)
admin.site.register(GetInTouch)
admin.site.register(HappyClients)
admin.site.register(HoursWorked)
admin.site.register(MyExpertise)
admin.site.register(MyPortfolioAiAndMachineLearning)
admin.site.register(MyPortfolioApps)
admin.site.register(MyPortfolioWebsites)
admin.site.register(MyResumeEducation)
admin.site.register(MyResumeExpertise)
admin.site.register(MyResumeSkills)
admin.site.register(MyResumeLanguages)
admin.site.register(PersonalInfo)
admin.site.register(ProjectFinished)
admin.site.register(SendAMessage)
admin.site.register(WhoAmI)
admin.site.register(WebsiteService)
admin.site.register(AppService)
admin.site.register(AIAndMachineService)
admin.site.register(HireMe)
admin.site.register(Facebook)
admin.site.register(Twitter)
admin.site.register(Instagram)
admin.site.register(Linkedin)
admin.site.register(Github)